ToDoApp/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include
from . import views

app_name = 'ToDoApp'

urlpatterns = [
    path('registration/', views.PersonRegistration.as_view(), name='registration'),
    path('create_task/', views.TaskCreateView.as_view(), name='create_task'),
    path('task_detail/', views.TaskList.as_view(), name='task_detail'),
    path('update_task/<int:pk>/', views.UpdateTaskView.as_view(), name='update_task'),
    path('delete_task/<int:pk>/', views.DeleteTaskView.as_view(), name='delete_task'),
    path('login/', views.PersonLogin.as_view(), name='login'),
    path('logout/', views.LogOut.as_view(), name='logout'),
    path('', views.MainView.as_view(), name='main'),

]

ToDoProject/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('todoproject/', include('ToDoApp.urls'))
]

ToDoApp/models.py
from django.db import models
from django.contrib.auth.models import User
from datetime import datetime
from django.urls import reverse

# Create your models here.


class Person(User):


    user_DOB = models.DateField(blank=False)
    REQUIRED_FIELDS = ['username', 'email', 'password']

    def __str__(self):
        return f"{self.first_name} {self.last_name}"


class Task(models.Model):
    task_title = models.CharField(max_length=200, blank=False)
    task_description = models.TextField(blank=True)
    is_complete = models.BooleanField(blank=False, default=False)

    # Category variables
    HT = 'Home Task'
    OT = 'Office Task'
    MISC = 'Miscellenious Task'

    category = [
        (HT , "Home Task"),
        (OT, "Office Task"),
        (MISC, 'Mescillineous')
    ]

    task_category = models.CharField(max_length=20, choices=category, blank=False)
    task_start_date = models.DateTimeField(default=datetime.now())
    task_end_date = models.DateTimeField(blank=True, null=True)
    person = models.ForeignKey(Person, on_delete=models.CASCADE)

    def get_absolute_url(self):
        return reverse('task_detail', kwargs={'pk': self.pk})

    def __str__(self):
        return self.task_title

ToDoApp/forms.py
from .models import Person, Task
from django import forms
from django.contrib.auth.forms import UserCreationForm

from django.forms.widgets import DateInput, PasswordInput
# Create your views here.
class RegistrationForm(UserCreationForm):

    class Meta:
        model = Person

        labels = {
            'user_DOB': ('D.O.B'),
        }
        widgets = {
            'user_DOB': DateInput(attrs={'type': 'date'})
        }

        fields = ['first_name', 'last_name', 'username', 'email', 'user_DOB']

        exclude = ['last_login', 'is_superuser', 'is_active', 'groups', 'user_permissions', 'date_joined', 'is_staff']


class TaskCreateForm(forms.ModelForm):

    class Meta:
        model = Task

        fields = '__all__'

        exclude = ['is_complete', 'task_start_date', 'task_end_date', 'person']
        # ['task_title', 'task_description', 'is_complete',
        #                   'task_category', 'task_start_date', 'task_end_date','person']

ToDoApp/views.py
from django.shortcuts import render
from datetime import date
import calendar
from django.urls import reverse_lazy
from django.http import HttpResponseRedirect

from .forms import RegistrationForm, TaskCreateForm
from .models import Person, Task
from django.views.generic.edit import FormView, CreateView, UpdateView, DeleteView
from django.views.generic.list import ListView
from django.contrib.auth.views import LoginView, TemplateView, LogoutView


# Create your views here.

class MainView(TemplateView):
    template_name = 'ToDoApp/main.html'


class PersonRegistration(CreateView):
    template_name = 'ToDoApp/register.html'
    form_class = RegistrationForm
    success_url = reverse_lazy('ToDoApp:main')

class PersonLogin(LoginView):
    template_name = 'ToDoApp/login.html'

    def get_redirect_url(self):
        return '/todoproject/task_detail/'


class TaskCreateView(CreateView):
    template_name = 'ToDoApp/create_task.html'
    form_class = TaskCreateForm
    success_url = '/todoproject/task_detail/'

    def form_valid(self, form):

        task = form.instance
        user = self.request.user
        person = Person.objects.filter(username=user)
        person = person[0]
        task.person = person
        task.save()
        self.object = task
        return HttpResponseRedirect(self.get_success_url())


class TaskList(ListView):
    model = Task

    def get_queryset(self):
        user = self.request.user
        user = Person.objects.filter(username=user)
        user = user[0]
        task = Task.objects.filter(person=user)
        return task

    def get(self, request, *args, **kwargs):
        self.object_list = self.get_queryset()
        my_date = date.today()
        today = calendar.day_name[my_date.weekday()]
        context = {
            'paginator' : None,
            'page_obj' : None,
            'is_paginated' : False,
            'object_list' : self.object_list,
            'my_date' : my_date,
            'today' : today
        }
        return self.render_to_response(context)


class UpdateTaskView(UpdateView):
    model = Task
    template_name = 'ToDoApp/update_task.html'
    fields = ['task_title', 'task_description', 'task_category']
    success_url = reverse_lazy('ToDoApp:task_detail')


class DeleteTaskView(DeleteView):
    template_name = 'ToDoApp/delete_task.html'
    model = Task
    context_object_name = 'task'
    success_url = reverse_lazy('ToDoApp:task_detail')


class LogOut(LogoutView):
    next_page = '/todoproject/'

ToDoApp/templates/ToDoApp/create_task.html
{% extends 'ToDoApp/login.html' %}

{% block content %}
<div id="login">
    <h3 class="text-center text-white pt-5">Add Task</h3>
    <div class="container">
        <div id="login-row" class="row justify-content-center align-items-center">
            <div id="login-column" class="col-md-6">
                <div id="login-box" class="col-md-12">
                    <form id="login-form" class="form" method="post">
                        {% csrf_token %}
                        <h2 class="text-center text-info" style="margin-left:-200px"><b>Add your Task</b></h2>

                        <div class="form-group">
                            <label class="text-info">
                                <table class="table">
                                    {{ form }}
                                </table>
                            </label>
                        </div>

                        <div>
                            <button type="submit" class="btn btn-primary">Submit</button>

                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock content %}

ToDoApp/templates/ToDoApp/delete_task.html
{% extends 'ToDoApp/login.html' %}

{% block content %}
<div id="login">
    <h3 class="text-center text-white pt-5">Delete Confirmation</h3>
    <div class="container">
        <div id="login-row" class="row justify-content-center align-items-center">
            <div id="login-column" class="col-md-6">
                <div id="login-box" class="col-md-12">
                    <form id="login-form" class="form" method="post">
                        {% csrf_token %}
                        <h2 class="text-center text-info" style="margin-left:-200px">

                        <p>Do you want to Delete Task</p>

                        <div>
                            <button type="submit" class="btn btn-danger">Yes</button>

                            <a href="{% url 'ToDoApp:task_detail' %}" style="margin-left:300px;">
                                <button class="btn btn-success" type="button">No</button>
                            </a>

                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock content %}




<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
    <form method="post">
        {% csrf_token %}
        <p>Do you want to delete task</p>
        <button type="submit">Yes</button>


    </form>

</body>
</html>

ToDoApp/templates/ToDoApp/login.html
<!doctype html>
<html lang="en">
<head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">


    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <link href="//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
    <script src="//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    {% block title %}
    <title>Login Page</title>
    {% endblock title %}
</head>
<body>
{% block content %}
<div id="login">
    <h3 class="text-center text-white pt-5">Login form</h3>
    <div class="container">
        <div id="login-row" class="row justify-content-center align-items-center">
            <div id="login-column" class="col-md-6">
                <div id="login-box" class="col-md-12">
                    <form id="login-form" class="form" method="post">
                        {% csrf_token %}
                        <h2 class="text-center text-info" style="margin-left:-200px"><b>Login</b></h2>

                        <div class="form-group">
                            <label class="text-info">
                                <table class="table">
                                    {{ form }}
                                </table>
                            </label>
                        </div>

                        <div >
                            <button type="submit" class="btn btn-primary">Login</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock content %}
</body>
</html>

ToDoApp/templates/ToDoApp/logout.html
<!doctype html>
<html lang="en">
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <link href="//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
    <script src="//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <!------ Include the above in your HEAD tag ---------->
    <title>Task Detail</title>
</head>
<body>
    <div class="container">
        <h1>Task Form</h1>
        <form method="POST" >
            {% csrf_token %}
            <table>
                {{ form }}
            </table>
            <button type="submit" class="btn btn-primary">Login</button>
        </form>
    </div>


</body>
</html>

ToDoApp/templates/ToDoApp/main.html
<!doctype html>
<html lang="en">
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <link href="//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
    <script src="//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <!------ Include the above in your HEAD tag ---------->
    <title>Hello, world!</title>
</head>
<body>


<body>
<div id="login">
    <h3 class="text-center text-white pt-5">Login form</h3>
    <div class="container">
        <div id="login-row" class="row justify-content-center align-items-center">
            <div id="login-column" class="col-md-8">


                <h1>Welcome to <span style="color:orange;">Arhamsoft</span> ToDo List App</h1>
                <br>
                <h3>Click on Below Button for Login or Register</h3>
                <br><br><br>
                <div>
                    <a href="{% url 'ToDoApp:login' %}">
                        <input type="submit" name="Login" class="btn btn-success btn-md" value="Login">
                    </a>
                    <a href="{% url 'ToDoApp:registration' %}" style="margin-left:400px">
                        <input type="submit" name="Register" class="btn btn-primary btn-md" value="Register">
                    </a>
                </div>

            </div>
        </div>
    </div>
</div>
</body>


</body>
</html>

ToDoApp/templates/ToDoApp/register.html
{% extends 'ToDoApp/login.html' %}

{% block title %}
<title>Register</title>
{% endblock title %}
{% block content %}

<div id="login">
    <div class="container">
        <div id="login-row" class="row justify-content-center align-items-center" style="margin-top:50px">
            <div id="login-column" class="col-md-6">
                <div id="login-box" class="col-md-12">
                    <form id="login-form" class="form" method="post">
                        {% csrf_token %}
                        <h2 class="text-center text-info" style="margin-left:-100px"><b>Registration Form</b></h2>

                        <div class="form-group">
                            <label class="text-info">
                                <table class="table">
                                    {{ form }}
                                </table>
                            </label>
                        </div>

                        <div >
                            <button type="submit" class="btn btn-primary">Register</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock content %}

ToDoApp/templates/ToDoApp/task_list.html
{% extends 'ToDoApp/login.html' %}

{% block content %}

<div id="login">

    <div class="holder d-flex align-items-center justify-content-center">

        <div class="container">

            <header class="text-center mb-2">
                <h1 class="display-4">Check list</h1>
            </header>

            <div class="row">
                <div class="col-lg-5 mx-auto">


                    <div class="card rounded border-0 shadow-sm position-relative">
                        <div class="card-body p-5">
                            <div class="d-flex align-items-center mb-4 pb-4 border-bottom"><i
                                    class="far fa-calendar-alt fa-3x"></i>
                                <div class="ms-3">

                                    <h3 class="text-uppercase fw-weight-bold mb-0"><b>{{today}}</b></h3>


                                    <p class="text-gray fst-italic mb-0">{{my_date}}</p>

                                    <a href="{% url 'ToDoApp:logout' %}" style="margin-left:250px;">
                                        <button class="btn btn-primary">Logout</button>
                                    </a>

                                </div>
                            </div>
                            <div class="form-check mb-3">
                                {% for task in object_list %}
                                <input class="form-check-input" id="flexCheck1" type="checkbox" checked>
                                <label class="form-check-label" for="flexCheck1">

                                    <span class="fst-italic pl-1"> <b> Task {{ forloop.counter }} --> {{ task }}</b></span>
                                    <br>

                                    <a href="{% url 'ToDoApp:update_task' task.id %}">
                                        <button style="margin-top:10px" class="btn btn-secondary">
                                            View
                                        </button>
                                    </a>

                                </label>
                                <br><br>
                                {% endfor %}
                            </div>
                            <a href="{% url 'ToDoApp:create_task' %}">
                                <button class="btn btn-primary">Add Task</button>
                            </a>

                        </div>
                    </div>
                </div>
            </div>
        </div>

    </div>
</div>

{% endblock content %}

ToDoApp/templates/ToDoApp/update_task.html
{% extends 'ToDoApp/login.html' %}

{% block content %}
<div id="login">
    <h3 class="text-center text-white pt-5">Login form</h3>
    <div class="container">
        <div id="login-row" class="row justify-content-center align-items-center">
            <div id="login-column" class="col-md-6">
                <div id="login-box" class="col-md-12">
                    <form id="login-form" class="form" method="post">
                        {% csrf_token %}
                        <h2 class="text-center text-info" style="margin-left:-200px"><b>View Task</b></h2>

                        <div class="form-group">
                            <label class="text-info">
                                <table class="table">
                                    {{ form }}
                                </table>
                            </label>
                        </div>

                        <div>
                            <button type="submit" class="btn btn-primary">Update</button>

                            <a href="{% url 'ToDoApp:delete_task' task.id%}" style="margin-left:300px;">
                                <button class="btn btn-danger" type="button">Delete</button>
                            </a>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock content %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
    <form method="post">
        {% csrf_token %}
        <table>
            {{ form }}
        </table>
        <button type="submit">Update</button>




    </form>

</body>
</html>